#!/usr/bin/env php
<?php

use App\Kernel;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

if (false === in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true)) {
   echo 'Warning: The console should be invoked via the CLI version of PHP, not the '.\PHP_SAPI.' SAPI'.\PHP_EOL;
}
set_time_limit(0);

$scriptFilename = $_SERVER["SCRIPT_FILENAME"];
$litRootDir = dirname($scriptFilename);
require $litRootDir.'/vendor/autoload.php';

if (!class_exists(Application::class)) {
   throw new RuntimeException('You need to add "symfony/console" as a Composer dependency.');
}

$input = new ArgvInput();
if (null !== $env = $input->getParameterOption(['--env', '-e'], null, true)) {
   putenv('APP_ENV='.$_SERVER['APP_ENV'] = $_ENV['APP_ENV'] = $env);
}

if ($input->hasParameterOption('--no-debug', true)) {
   putenv('APP_DEBUG='.$_SERVER['APP_DEBUG'] = $_ENV['APP_DEBUG'] = '0');
}

//if ($_SERVER['APP_DEBUG']) {
//   umask(0000);
//   if (class_exists(Debug::class)) {
//      Debug::enable();
//   }
//}

$_SERVER['APP_ENV'] = "dev";
$_SERVER['APP_DEBUG'] = true;
$application = new Application();
$application->run($input);
