/*                                                                -*- C -*-
   +----------------------------------------------------------------------+
   | PHP Version 7                                                        |
   +----------------------------------------------------------------------+
   | Copyright (c) 1997-2018 The PHP Group                                |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
   | Author: Stig Sæther Bakken <ssb@php.net>                             |
   +----------------------------------------------------------------------+
*/

// This source file is part of the polarphp.org open source project
//
// Copyright (c) 2017 - 2018 polarphp software foundation
// Copyright (c) 2017 - 2018 zzu_softboy <zzu_softboy@163.com>
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://polarphp.org/LICENSE.txt for license information
// See https://polarphp.org/CONTRIBUTORS.txt for the list of polarphp project authors
//
// Created by polarboy on 2018/12/20.
//
// Warning: this file generated by polarphp build system, do not modify.

#cmakedefine PEAR_INSTALLDIR         ""
#cmakedefine PHP_INCLUDE_PATH        ""
#cmakedefine PHP_EXTENSION_DIR       ""
#cmakedefine PHP_PREFIX              ""
#cmakedefine PHP_BINDIR              ""
#cmakedefine PHP_SBINDIR             ""
#cmakedefine PHP_MANDIR              ""
#cmakedefine PHP_LIBDIR              ""
#cmakedefine PHP_DATADIR             ""
#cmakedefine PHP_SYSCONFDIR          ""
#cmakedefine PHP_LOCALSTATEDIR       ""
#cmakedefine POLARPHP_CONFIG_FILE_PATH    "@POLARPHP_CONFIG_FILE_PATH@"
#cmakedefine POLARPHP_CONFIG_FILE_SCAN_DIR    "@POLARPHP_CONFIG_FILE_SCAN_DIR@"
#cmakedefine PHP_SHLIB_SUFFIX        ""
#cmakedefine PHP_SHLIB_EXT_PREFIX    ""
