/*                                                                -*- C -*-
   +----------------------------------------------------------------------+
   | PHP Version 7                                                        |
   +----------------------------------------------------------------------+
   | Copyright (c) 1997-2018 The PHP Group                                |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.php.net/license/3_01.txt                                  |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
   | Author: Stig Sæther Bakken <ssb@php.net>                             |
   +----------------------------------------------------------------------+
*/

// This source file is part of the polarphp.org open source project
//
// Copyright (c) 2017 - 2018 polarphp software foundation
// Copyright (c) 2017 - 2018 zzu_softboy <zzu_softboy@163.com>
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://polarphp.org/LICENSE.txt for license information
// See https://polarphp.org/CONTRIBUTORS.txt for the list of polarphp project authors
//
// Created by polarboy on 2018/12/20.
//
// Warning: this file generated by polarphp build system, do not modify.

#define POLARPHP_INCLUDE_PATH                 "@POLAR_DEFAULT_INCLUDE_DIR@"
#define POLARPHP_BINARY                       "@POLAR_EXECUTABLE_FILEPATH@"
#define POLARPHP_EXTENSION_DIR                ""
#define POLARPHP_PREFIX                       "@POLAR_BINARY_DIR@"
#define POLARPHP_BINDIR                       "@POLAR_INSTALL_BIN_DIR@"
#define POLARPHP_LIBDIR                       "@POLAR_INSTALL_LIB_DIR@"
#define POLARPHP_DATADIR                      "@POLAR_INSTALL_DATA_DIR@"
#define POLARPHP_MAN_DIR                      "@POLAR_INSTALL_MAN_DIR@"
#define POLARPHP_SYSCONFDIR                   "@POLAR_INSTALL_CFG_DIR@"
#define POLARPHP_LOCALSTATEDIR                "@POLAR_INSTALL_LOCAL_STATE_DIR@"
#define POLARPHP_CONFIG_FILE_PATH             "@POLARPHP_CONFIG_FILE_PATH@"
#define POLARPHP_CONFIG_FILE_SCAN_DIR         "@POLARPHP_CONFIG_FILE_SCAN_DIR@"
#define POLARPHP_SHLIB_SUFFIX                 "@CMAKE_SHARED_LIBRARY_SUFFIX@"
#define POLARPHP_SHLIB_EXT_SUFFIX             "@CMAKE_SHARED_MODULE_SUFFIX@"
