/* automatically generated by cmake */
/* edit CMakeLists.txt to change version number */

#cmakedefine PHP_MAJOR_VERSION @POLAR_VERSION_MAJOR@
#cmakedefine PHP_MINOR_VERSION @POLAR_VERSION_MINOR@
#cmakedefine PHP_RELEASE_VERSION @POLAR_VERSION_RELEASE@
#cmakedefine PHP_EXTRA_VERSION "@POLAR_VERSION_EXTRA@"
#cmakedefine PHP_VERSION "@POLAR_PACKAGE_VERSION@"
#cmakedefine PHP_VERSION_ID @POLAR_VERSION_ID@
