// This source file is part of the polarphp.org open source project
//
// Copyright (c) 2017 - 2018 polarphp software foundation
// Copyright (c) 2017 - 2018 zzu_softboy <zzu_softboy@163.com>
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://polarphp.org/LICENSE.txt for license information
// See https://polarphp.org/CONTRIBUTORS.txt for the list of polarphp project authors
//
// Created by polarboy on 2018/12/25.

#ifndef POLARPHP_GLOBAL_PHP_VERSION_H
#define POLARPHP_GLOBAL_PHP_VERSION_H

/* automatically generated by cmake */
/* edit CMakeLists.txt to change version number */

#define PHP_MAJOR_VERSION @PHP_VERSION_MAJOR@
#define PHP_MINOR_VERSION @PHP_VERSION_MINOR@
#define PHP_RELEASE_VERSION @PHP_VERSION_RELEASE@
#define PHP_EXTRA_VERSION "@PHP_VERSION_EXTRA@"
#define PHP_VERSION "@PHP_PACKAGE_VERSION@"
#define PHP_VERSION_ID @PHP_VERSION_ID@

#define POLARPHP_PACKAGE_NAME      "@POLAR_PACKAGE_NAME@"
#define POLARPHP_VERSION_MAJOR      @POLAR_VERSION_MAJOR@
#define POLARPHP_VERSION_MINOR      @POLAR_VERSION_MINOR@
#define POLARPHP_VERSION_PATCH      @POLAR_VERSION_PATCH@
#define POLARPHP_VERSION_SUFFIX    "@POLAR_VERSION_SUFFIX@"
#define POLARPHP_VERSION           "@POLAR_VERSION@"
#define POLARPHP_PACKAGE_STRING    "@POLAR_PACKAGE_STRING@"
#define POLARPHP_VERSION_ID         @POLAR_VERSION_ID@
#define POLARPHP_PACKAGE_BUGREPORT "@POLAR_PACKAGE_BUGREPORT@"

#endif // POLARPHP_GLOBAL_PHP_VERSION_H
