// This source file is part of the polarphp.org open source project
//
// Copyright (c) 2017 - 2018 polarphp software foundation
// Copyright (c) 2017 - 2018 zzu_softboy <zzu_softboy@163.com>
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://polarphp.org/LICENSE.txt for license information
// See https://polarphp.org/CONTRIBUTORS.txt for the list of polarphp project authors
//
// Created by polarboy on 2018/08/28.
//
// Warning: this file generated by polarphp build system, do not modify.

#ifndef POLAR_DEVLTOOLS_LIT_CONFIG_H
#define POLAR_DEVLTOOLS_LIT_CONFIG_H

#cmakedefine POLAR_LIT_VERSION "@POLAR_LIT_VERSION@"
#cmakedefine POLAR_OS "@POLAR_OS@"
#cmakedefine POLAR_LIT_RUNTIME_DIR "@POLAR_LIT_RUNTIME_DIR@"
#cmakedefine POLAR_OS_MACOS
#cmakedefine POLAR_OS_DARWIN
#cmakedefine POLAR_OS_UNIX
#cmakedefine POLAR_OS_WIN32
#cmakedefine POLAR_OS_CYGWIN
#cmakedefine POLAR_OS_MINGW
#cmakedefine CURSES_HAVE_CURSES_H
#cmakedefine CURSES_HAVE_NCURSES_H
#cmakedefine CURSES_HAVE_NCURSES_NCURSES_H
#cmakedefine CURSES_HAVE_NCURSES_CURSES_H

#ifdef CURSES_HAVE_NCURSES_H
#include <ncurses.h>
#elif defined(CURSES_HAVE_CURSES_H)
#include <curses.h>
#elif defined(CURSES_HAVE_NCURSES_NCURSES_H)
#include <ncurses/ncurses.h>
#elif defined(CURSES_HAVE_NCURSES_CURSES_H)
#include <ncurses/curses.h>
#endif

#endif // POLAR_DEVLTOOLS_LIT_CONFIG_H
