// This source file is part of the polarphp.org open source project
//
// Copyright (c) 2017 - 2018 polarphp software foundation
// Copyright (c) 2017 - 2018 zzu_softboy <zzu_softboy@163.com>
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See http://polarphp.org/LICENSE.txt for license information
// See http://polarphp.org/CONTRIBUTORS.txt for the list of polarphp project authors
//
// Created by polarboy on 2018/10/08.
//
// Warning: this file generated by polarphp build system, do not modify.

#ifndef POLAR_DEVLTOOLS_UTILS_UTILS_CONFIG_H
#define POLAR_DEVLTOOLS_UTILS_UTILS_CONFIG_H

/* Define to 1 if you have the `getrusage' function. */
#cmakedefine01 HAVE_GETRUSAGE

/* Define to 1 if you have the `getpagesize' function. */
#cmakedefine01 HAVE_GETPAGESIZE

/* Define to 1 if you have the `isatty' function. */
#cmakedefine01 HAVE_ISATTY

/* Define to 1 if you have the `futimens' function. */
#cmakedefine01 HAVE_FUTIMENS

/* Define to 1 if you have the `futimes' function. */
#cmakedefine01 HAVE_FUTIMES

/* Define to 1 if you have the `lseek64' function. */
#cmakedefine01 HAVE_LSEEK64

/* Define to 1 if you have the <mach/mach.h> header file. */
#cmakedefine01 HAVE_MACH_MACH_H

/* Define to 1 if you have the `mallctl' function. */
#cmakedefine01 HAVE_MALLCTL

/* Define to 1 if you have the `mallinfo' function. */
#cmakedefine01 HAVE_MALLINFO

/* Define to 1 if you have the <malloc.h> header file. */
#cmakedefine01 HAVE_MALLOC_H

/* Define to 1 if you have the <malloc/malloc.h> header file. */
#cmakedefine01 HAVE_MALLOC_MALLOC_H

/* Define to 1 if you have the `malloc_zone_statistics' function. */
#cmakedefine01 HAVE_MALLOC_ZONE_STATISTICS

/* Define to 1 if you have the `sysconf' function. */
#cmakedefine01 HAVE_SYSCONF

/* Define to 1 if you have the `sbrk' function. */
#cmakedefine01 HAVE_SBRK

/* Define to 1 if you have the `setenv' function. */
#cmakedefine01 HAVE_SETENV

/* Define to 1 if you have the <signal.h> header file. */
#cmakedefine01 HAVE_SIGNAL_H

/* Define to 1 if you have the <errno.h> header file. */
#cmakedefine01 HAVE_ERRNO_H

/* Define to 1 if you have the declaration of `strerror_s', and to 0 if you
   don't. */
#cmakedefine01 HAVE_DECL_STRERROR_S

/* Define to 1 if you have the `strerror' function. */
#cmakedefine01 HAVE_STRERROR

/* Define to 1 if you have the `strerror_r' function. */
#cmakedefine01 HAVE_STRERROR_R

/* Define to 1 if you have the `setrlimit' function. */
#cmakedefine01 HAVE_SETRLIMIT

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#cmakedefine01 HAVE_SYS_IOCTL_H

/* Define to 1 if you have the <sys/mman.h> header file. */
#cmakedefine01 HAVE_SYS_MMAN_H

/* Define to 1 if you have the <sys/param.h> header file. */
#cmakedefine01 HAVE_SYS_PARAM_H

/* Define to 1 if you have the <sys/resource.h> header file. */
#cmakedefine01 HAVE_SYS_RESOURCE_H

/* Define to 1 if you have the <sys/stat.h> header file. */
#cmakedefine01 HAVE_SYS_STAT_H

/* Define to 1 if you have the <sys/time.h> header file. */
#cmakedefine01 HAVE_SYS_TIME_H

/* Define to 1 if you have the <sys/types.h> header file. */
#cmakedefine01 HAVE_SYS_TYPES_H

/* Define to 1 if you have the <unistd.h> header file. */
#cmakedefine01 HAVE_UNISTD_H

/* Define to 1 if you have the <valgrind/valgrind.h> header file. */
#cmakedefine01 HAVE_VALGRIND_VALGRIND_H

#endif // POLAR_DEVLTOOLS_UTILS_UTILS_CONFIG_H
